const WomenCollection = [
    {
        _id:"101",
        name:"Looney Tunes: Bugs Bunny",
        title:"Boyfriend T-Shirts",
        displayImage:"./img/WomenCollection1.webp",
        alt:"Women-Product",
        price:"899",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1499/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"102",
        name:"Minions: Blah Blah Blah",
        title:"Boyfriend T-Shirts",
        displayImage:"./img/WomenCollection2.webp",
        alt:"Women-Product",
        price:"599",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"103",
        name:"Scooby Doo: Jeebiesville",
        title:"Boyfriend T-Shirts",
        displayImage:"./img/WomenCollection3.webp",
        alt:"Women-Product",
        price:"699",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1599/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"104",
        name:"Naruto: Gaara",
        title:"Boyfriend T-Shirts",
        displayImage:"./img/WomenCollection4.webp",
        alt:"Women-Product",
        price:"999",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"105",
        name:"Kung Fu Panda: Skadoosh",
        title:"Boyfriend T-Shirts",
        displayImage:"./img/WomenCollection5.webp",
        alt:"Women-Product",
        price:"899",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 999/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"106",
        name:"TSS Originals: Real Nareal",
        title:"Boyfriend T-Shirts",
        displayImage:"./img/WomenCollection6.webp",
        alt:"Women-Product",
        price:" 499",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 799/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"107",
        name:"Rick And Morty: Aw Geez",
        title:"Boyfriend T-Shirts",
        displayImage:"./img/WomenCollection4.webp",
        alt:"Women-Product",
        price:" 599",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 999/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"108",
        name:"Popeye: Don't Mess With Me",
        title:"Boyfriend T-Shirts",
        displayImage:"./img/WomenCollection8.webp",
        alt:"Women-Product",
        price:" 899",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"109",
        name:"Solids: Green Ash",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection9.webp",
        alt:"Women-Product",
        price:" 1299",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"110",
        name:"Solids: Green Ash",
        title:"Women Boyfriend T-Shirts",
        displayImage:"./img/WomenCollection10.webp",
        alt:"Women-Product",
        price:" 1299",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"111",
        name:"Solids: Green Ash",
        title:"Women Boyfriend T-Shirts",
        displayImage:"./img/WomenCollection11.webp",
        alt:"Women-Product",
        price:" 1899",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 2199/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"112",
        name:"The Little Mermaid: Mosaic",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection12.webp",
        alt:"Women-Product",
        price:" 1799",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1899/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"113",
        name:"Solids: Green Ash",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection13.webp",
        alt:"Women-Product",
        price:" 99",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"114",
        name:"Linen: Coral",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection14.webp",
        alt:"Women-Product",
        price:" 1299",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"115",
        name:"Plaid: Pink Jade",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection15.webp",
        alt:"Women-Product",
        price:" 1599",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1899/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"116",
        name:"Kung Fu Panda: Fearless",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection16.webp",
        alt:"Women-Product",
        price:"1299",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"117",
        name:"Linen: Azure Blue",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection17.webp",
        alt:"Women-Product",
        price:" 1399",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"118",
        name:"Plaid: Viridis And Raspberry",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection18.webp",
        alt:"Women-Product",
        price:" 1599",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1699/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"119",
        name:"Linen: Dusky Rose",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection19.webp",
        alt:"Women-Product",
        price:" 1299",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"120",
        name:"Linen: Off White",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection20.webp",
        alt:"Women-Product",
        price:" 1299",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"121",
        name:"Solids: Sunshine",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection21.webp",
        alt:"Women-Product",
        price:" 1299",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"122",
        name:"Solids: Pastel Shades",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection22.webp",
        alt:"Women-Product",
        price:" 1299",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"123",
        name:"Solids: Girl Gang",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection23.webp",
        alt:"Women-Product",
        price:" 1299",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"124",
        name:"Solids: Green Ash",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection24.webp",
        alt:"Women-Product",
        price:" 899",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"125",
        name:"Solids: Red and Black",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection25.webp",
        alt:"Women-Product",
        price:" 899",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"126",
        name:"Solids: White and Black",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection26.webp",
        alt:"Women-Product",
        price:" 1299",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"127",
        name:"Solids: Blue and White",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection27.webp",
        alt:"Women-Product",
        price:" 1199",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    },
    {
        _id:"128",
        name:"Solids: Wintages Stamps",
        title:"Women Boyfriend Shirts",
        displayImage:"./img/WomenCollection28.webp",
        alt:"Women-Product",
        price:" 699",
        brand:"Brooklyn Nine-Nine: 99th Precinct",
        description:"Shop for official licensed Brooklyn Nine-Nine Merch exclusively at The Souled Store.",
        RodePrice:"Rs. 1399/- incl. of all taxes",
        productDetais:"Premium Heavy Gauge Fabric 100% Cotton Machine Wash"
    }

];

export default WomenCollection;